[phases.setup]
nixPkgs = ['nodejs_20', 'nodePackages.npm']

[phases.install]
cmds = ['/usr/bin/npm install']

[phases.build]
cmds = ['/usr/bin/npm install', '/usr/bin/npm run build']

[start]
cmd = '/usr/bin/npm run start'

[build]
src = '.'
nodeVersion = '20'
buildCommand = '/usr/bin/npm install && /usr/bin/npm run build'
startCommand = '/usr/bin/npm run start' 