[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd /app && npm install']

[phases.build]
cmds = ['cd /app && npm run build']

[start]
cmd = 'cd /app && npm run start'

[build]
src = '.'
nodeVersion = '20'